apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: NodePort
  selector:
    app: shopping-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007

